spring:
  application:
    name: job-service
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/jobs_db
    username: jobber
    password: jobberPass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      okhttp:
        enabled: true

eureka:
  instance:
    metadata-map:
      configPath: /jobs-app/api/
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  topics:
    appsub: application.submitted
    buslog: logs.business

server:
  port: 0
  servlet:
    context-path: /jobs-app/api/

info:
  app:
    name: Job Service
    description: This microservice for managing jobs.

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"