spring:
  application:
    name: JOB-SERVICE

  elasticsearch:
    uris: http://localhost:9200
    username: jobelastic
    password: passwordJob

  data:
    elasticsearch:
      repositories:
        enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: job-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    home-page-url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/

app:
  topics:
    log-info: logs.info
    log-error: logs.error
    job-request: job.req
    job-response: job.res

server:
  port: 0
  servlet:
    context-path: /jobs-app/api

info:
  app:
    name: Job Service
    description: This microservice for managing jobs.

management:
  endpoints:
    web:
      exposure:
        include: "*"