spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: identity-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    openfeign:
      okhttp:
        enabled: true

eureka:
  instance:
    metadata-map:
      configPath: /identity-app/api
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  topics:
    log-info: logs.info
    log-error: logs.error
  jwt:
    secret-key: Zw1dsOA1hqSKlX9PVREovrt2S0h8AydmIvb4FwC/Ij4=
    expiration: 86400000

server:
  port: 0
  servlet:
    context-path: /identity-app/api

info:
  app:
    name: Identity Service
    description: This microservice for managing authentication and authorization users.

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"