spring:
  application:
    name: users-service

  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  topics:
    application-new: application.created
    application-upd: application.changed
    log-info: logs.info
    log-error: logs.error

    interview: interview-events
    job: job-events
    user: user-events

server:
  port: 8081