spring:
  application:
    name: workflow-service
  datasource:
    url: jdbc:postgresql://localhost:5434/workflow_db
    username: postgres
    password: workflowpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: workflow-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      okhttp:
        enabled: true

eureka:
  instance:
    metadata-map:
      configPath: /workflow/api/
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0
  servlet:
    context-path: /workflow/api/

info:
  app:
    name: Workflow Service
    description: This microservice for managing applies for job and interviews.

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
