spring:
  application:
    name: WORKFLOW-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5434/workflow_db
    username: postgres
    password: workflowpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: workflow-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    home-page-url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/

app:
  topics:
    application-new: application.created
    application-upd: application.changed
    log-info: logs.info
    log-error: logs.error
    job-request: job.req
    job-response: job.res

    interview: interview-events


server:
  port: 0
  servlet:
    context-path: /workflow-app/api

info:
  app:
    name: Workflow Service
    description: This microservice for managing applies for job and interviews.

management:
  endpoints:
    web:
      exposure:
        include: "*"